#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-YAML-LibYAML
Version  : 0.70
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/T/TI/TINITA/YAML-LibYAML-0.70.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/T/TI/TINITA/YAML-LibYAML-0.70.tar.gz
Summary  : 'Perl YAML Serialization using XS and libyaml'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-YAML-LibYAML-lib
Requires: perl-YAML-LibYAML-man

%description
NAME
YAML::XS - Perl YAML Serialization using XS and libyaml
SYNOPSIS
use YAML::XS;

my $yaml = Dump [ 1..4 ];
my $array = Load $yaml;

%package lib
Summary: lib components for the perl-YAML-LibYAML package.
Group: Libraries

%description lib
lib components for the perl-YAML-LibYAML package.


%package man
Summary: man components for the perl-YAML-LibYAML package.
Group: Default

%description man
man components for the perl-YAML-LibYAML package.


%prep
%setup -q -n YAML-LibYAML-0.70

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/YAML/LibYAML.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/YAML/LibYAML.pod
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/YAML/XS.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/YAML/XS.pod
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/YAML/XS/LibYAML.pm

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/auto/YAML/XS/LibYAML/LibYAML.so

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/YAML::LibYAML.3
/usr/share/man/man3/YAML::XS.3
/usr/share/man/man3/YAML::XS::LibYAML.3
